name = "PlonkLean"
defaultTargets = ["PlonkLean", "Tests"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[[lean_lib]]
name = "PlonkLean"

[[lean_lib]]
name = "Tests"
